name = "Delaunator"
uuid = "466f8f70-d5e3-4806-ac0b-a54b75a91218"
authors = ["David Gleich", "Steve Kelly"]
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[targets]
test = ["Aqua", "GeometryBasics", "JET", "JSON", "Test", "StableRNGs"]
